import type { StatusReportItem } from '../types/statusReport.types'

export const SEED_ITEMS: Omit<StatusReportItem, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'seed-1',
    title: 'FGTS – Tombamento PANCP para nova plataforma',
    section: 'sprint', priority: 'high',
    stacks: ['ios', 'android', 'bff'],
    resp: 'Time Mobile', pct: 76,
    startDate: '2026-02-03', durationDays: 25, deadlineDate: '',
    dependsOn: [],
    jira: '', notes: 'iOS. Versão 3.2 homologada\nAndroid. Versão 3.0 em ajuste\n76% modelagem concluída',
  },
  {
    id: 'seed-2',
    title: 'Privado – Retenção de clientes',
    section: 'sprint', priority: 'high',
    stacks: ['ios', 'android'],
    resp: '', pct: 60,
    startDate: '2026-02-10', durationDays: 14, deadlineDate: '',
    dependsOn: [],
    jira: '', notes: '',
  },
  {
    id: 'seed-3',
    title: 'Privado – Alteração de parcela consignado',
    section: 'sprint', priority: 'medium',
    stacks: ['back'],
    resp: '', pct: 40,
    startDate: '', durationDays: 10, deadlineDate: '',
    dependsOn: ['seed-2'],
    jira: '', notes: '',
  },
  {
    id: 'seed-4',
    title: 'WL – Consignado Privado (onboarding)',
    section: 'sprint', priority: 'medium',
    stacks: ['ios', 'android', 'bff', 'back'],
    resp: '', pct: 30,
    startDate: '', durationDays: 20, deadlineDate: '',
    dependsOn: ['seed-3'],
    jira: '', notes: 'Tela de identificação\nTela de proposta\nIntegração BFF',
  },
  {
    id: 'seed-5',
    title: 'Ajuste retorno CDC',
    section: 'implanted', priority: 'low',
    stacks: ['back'], resp: '', pct: 100,
    startDate: '2026-02-11', durationDays: 3, deadlineDate: '',
    dependsOn: [], jira: '', notes: '',
  },
  {
    id: 'seed-6',
    title: 'Privado/FGTS – Biometria facial',
    section: 'implanted', priority: 'low',
    stacks: ['ios', 'android'], resp: '', pct: 100,
    startDate: '2026-02-11', durationDays: 5, deadlineDate: '',
    dependsOn: [], jira: '', notes: '',
  },
  {
    id: 'seed-7',
    title: 'Privado – Ajuste tela de empréstimo',
    section: 'debitos', priority: 'high',
    stacks: ['bff', 'back'], resp: '', pct: 20,
    startDate: '2026-02-20', durationDays: 8, deadlineDate: '',
    dependsOn: [], jira: '', notes: 'Priorização freezing\nDependência infra',
  },
  {
    id: 'seed-8',
    title: 'Privado – Toast de confirmação',
    section: 'teste', priority: 'medium',
    stacks: ['ios', 'android'], resp: 'QA', pct: 50,
    startDate: '2026-02-18', durationDays: 5, deadlineDate: '',
    dependsOn: [], jira: '', notes: '',
  },
  {
    id: 'seed-9',
    title: 'Privado – Recálculo de parcela',
    section: 'teste', priority: 'high',
    stacks: ['bff', 'back'], resp: 'QA', pct: 0,
    startDate: '', durationDays: 7, deadlineDate: '',
    dependsOn: ['seed-8'],
    jira: '', notes: '',
  },
  {
    id: 'seed-10',
    title: 'FGTS – Migração de conta',
    section: 'backlog', priority: 'medium',
    stacks: ['ios', 'android', 'bff', 'back'], resp: '', pct: 0,
    startDate: '', durationDays: 15, deadlineDate: '',
    dependsOn: ['seed-1'],
    jira: '', notes: '',
  },
]
